### ISSUE TITLE
java.lang.NullPointerException in Section UUC of taplint tests

### ISSUE THREAD

**Issue by esabol** [Starlink/starjava#63]
Hi, Mark. I just upgraded our stilts.jar to v3.4-4, and got a `java.lang.NullPointerException` when running taplint. Obviously, we didn't get this error with v3.4-3, and we run taplint frequently (like daily), so it's specific to v3.4-4.
```
Section UUC: Check column units and UCDs are legal
I-UUC-UCDV-1 UCD validation details: Ucidy version 1.2, UCD words version EN-UCD1+-1.4, UCD deprecated words version EN-UCD1+-1.4
java.lang.NullPointerException
        at uk.ac.starlink.ttools.votlint.UnitStatus.createStatus(UnitStatus.java:109)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
        at uk.ac.starlink.ttools.votlint.UnitStatus.getStatus(UnitStatus.java:69)
        at uk.ac.starlink.ttools.taplint.UnitUcdStage.lambda$createUnitChecker$0(UnitUcdStage.java:171)
        at uk.ac.starlink.ttools.taplint.UnitUcdStage.reportBadValues(UnitUcdStage.java:113)
        at uk.ac.starlink.ttools.taplint.UnitUcdStage.run(UnitUcdStage.java:78)
        at uk.ac.starlink.ttools.taplint.TapLinter$4.execute(TapLinter.java:259)
        at uk.ac.starlink.ttools.task.LineInvoker.invoke(LineInvoker.java:303)
        at uk.ac.starlink.ttools.Stilts.main(Stilts.java:50)
```

**Comment by mbtaylor** [comment]
Oh dear, you seem to have caught a crab, sorry about that.  This is related to some new code that attempts to provide better advice about what an unrecognised unit probably ought to look like, but it fails for units which are unknown in VOUnits syntax but recognised in some other unit syntax variants.

I've made a fix at fb1a7b3d; this will be in the next public release, but until then you can find a pre-release version with the fix at http://andromeda.star.bristol.ac.uk/releases/stilts/pre/stilts.jar . If you don't want to do that you can revert to v3.4-3.

**Comment by esabol** [comment]
Thanks, Mark. I've downloaded your pre-release stilts.jar, and it works great. Thanks for the quick fix. Closing.

**Comment by mbtaylor** [comment]
Thanks a lot for reporting the issue.
