### ISSUE TITLE
[ttools-3.4.9] NullPointerException in PrintSaxMessager during test

### ISSUE THREAD

**Issue by olebole** [Starlink/starjava#67]
When running the VersionDetailTest, I get the following exception with the latest ttools release (3.4.9):
```
Testcase: testVersions(uk.ac.starlink.ttools.votlint.VersionDetailTest):	Caused an ERROR
Cannot invoke "java.io.PrintStream.println(String)" because "this.out_" is null
java.lang.NullPointerException: Cannot invoke "java.io.PrintStream.println(String)" because "this.out_" is null
	at uk.ac.starlink.ttools.votlint.PrintSaxMessager.reportMessage(PrintSaxMessager.java:75)
	at uk.ac.starlink.ttools.votlint.VotLintContext.warning(VotLintContext.java:257)
	at uk.ac.starlink.ttools.votlint.VersionDetail.getInstance(VersionDetail.java:118)
	at uk.ac.starlink.ttools.votlint.VersionDetailTest.getDetail(VersionDetailTest.java:34)
	at uk.ac.starlink.ttools.votlint.VersionDetailTest.testVersions(VersionDetailTest.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
The reason seems that in VersionDetailTest, the PrintSaxMessager is constructed as https://github.com/Starlink/starjava/blob/778c74aeb936160775352926c812f01e66297fa4/ttools/src/testcases/uk/ac/starlink/ttools/votlint/VersionDetailTest.java#L33

which sets the `_outl` attribute to `null`. Any attempt to print a warning will then ofcourse create the NPE: https://github.com/Starlink/starjava/blob/778c74aeb936160775352926c812f01e66297fa4/ttools/src/main/uk/ac/starlink/ttools/votlint/PrintSaxMessager.java#L74-L75

I am not sure why I create a warning here which was not in your CI tests; this may happen because of some slightly different versions (ADQLLib?); however maybe the `_outl` attribute should probably be checked for null before used (or a real output stream should applied in the test?)

**Comment by mbtaylor** [comment]
@olebole you are quite right.  Fixed in 417ed4eab.  Many thanks for the report.
